<?php
require_once __DIR__.'/../config/database.php';
require_once __DIR__.'/MockIntegrationAdapter.php';
require_once __DIR__.'/../models/Procurement.php';

class ReliabilityService {
    private static function fingerprint(string $type, ?int $orderId, string $detail): string { return hash('sha256', $type.'|'.($orderId??0).'|'.$detail); }
    public static function claimOutbox(int $limit=25): array {
        $db=getDB();$limit=min(100,max(1,$limit));$db->beginTransaction();
        try{$q=$db->query("SELECT * FROM outbox_events WHERE status IN ('pending','failed') AND available_at<=NOW() AND attempts<max_attempts ORDER BY id ASC LIMIT {$limit} FOR UPDATE");$rows=$q->fetchAll();$u=$db->prepare('UPDATE outbox_events SET attempts=attempts+1 WHERE id=:id');foreach($rows as $row)$u->execute(['id'=>$row['id']]);$db->commit();return $rows;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
    }
    public static function runWorker(int $limit=25): array {
        $rows=self::claimOutbox($limit);$db=getDB();$result=['claimed'=>count($rows),'published'=>0,'failed'=>0,'dead_letter'=>0,'events'=>[]];
        foreach($rows as $row){$payload=json_decode($row['payload'],true)?:[];$event=['event_id'=>$row['event_id'],'event_type'=>$row['event_type'],'aggregate_id'=>$row['aggregate_id'],'payload'=>$payload];$adapter=MockIntegrationAdapter::publish($event);if($adapter['status']==='success'){$q=$db->prepare("UPDATE outbox_events SET status='published',destination='local_mock',delivery_mode='mock',published_at=NOW(),last_error=NULL WHERE id=:id");$q->execute(['id'=>$row['id']]);$result['published']++;$result['events'][]=['event_id'=>$row['event_id'],'status'=>'published','reference'=>$adapter['reference']];}else{$attempts=(int)$row['attempts']+1;$terminal=$attempts>=(int)$row['max_attempts'];$q=$db->prepare("UPDATE outbox_events SET status=:status,last_error=:error,available_at=DATE_ADD(NOW(),INTERVAL :delay SECOND) WHERE id=:id");$q->bindValue(':status',$terminal?'dead_letter':'failed');$q->bindValue(':error',$adapter['message']);$q->bindValue(':delay',min(3600,30*max(1,$attempts)),PDO::PARAM_INT);$q->bindValue(':id',$row['id'],PDO::PARAM_INT);$q->execute();$result[$terminal?'dead_letter':'failed']++;$result['events'][]=['event_id'=>$row['event_id'],'status'=>$terminal?'dead_letter':'failed'];}}
        return $result;
    }
    public static function replay(string $eventId): array {$db=getDB();$q=$db->prepare("UPDATE outbox_events SET status='pending',attempts=0,last_error=NULL,available_at=NOW() WHERE event_id=:eid AND status IN ('failed','dead_letter')");$q->execute(['eid'=>$eventId]);return $q->rowCount()?['status'=>'success','message'=>'Event dijadwalkan ulang.']:['status'=>'error','message'=>'Event gagal tidak ditemukan.'];}
    public static function recordInbox(string $source,string $eventId,string $type,array $payload): array {$db=getDB();try{$q=$db->prepare('INSERT INTO inbox_events(event_id,source_system,event_type,payload) VALUES(:eid,:source,:type,:payload)');$q->execute(['eid'=>$eventId,'source'=>$source,'type'=>$type,'payload'=>json_encode($payload)]);return ['status'=>'success','idempotent_replay'=>false];}catch(PDOException $e){if($e->getCode()==='23000')return ['status'=>'success','idempotent_replay'=>true];throw $e;}}
    public static function recordWebhook(string $provider,string $eventId,string $raw,string $signature,string $status,?string $error=null): void {$db=getDB();$q=$db->prepare('INSERT INTO webhook_receipts(provider,event_id,signature_hash,payload_hash,status,error_message) VALUES(:provider,:eid,:sig,:payload,:status,:error) ON DUPLICATE KEY UPDATE status=VALUES(status),error_message=VALUES(error_message)');$q->execute(['provider'=>$provider,'eid'=>$eventId,'sig'=>hash('sha256',$signature),'payload'=>hash('sha256',$raw),'status'=>$status,'error'=>$error]);}
    public static function reconcile(): array {$db=getDB();$found=[];$q=$db->query("SELECT id,order_code,status,payment_status,created_at FROM orders WHERE payment_status='pending' AND created_at<DATE_SUB(NOW(),INTERVAL 15 MINUTE)");foreach($q->fetchAll() as $o)$found[]=self::issue('PAYMENT_PENDING_TIMEOUT',(int)$o['id'],'warning',['order_code'=>$o['order_code'],'payment_status'=>$o['payment_status']]);$q=$db->query("SELECT id,order_code,status,paid_at FROM orders WHERE status IN ('paid','processing') AND paid_at IS NOT NULL AND paid_at<DATE_SUB(NOW(),INTERVAL 30 MINUTE) AND shipped_at IS NULL");foreach($q->fetchAll() as $o)$found[]=self::issue('SHIPMENT_MISSING',(int)$o['id'],'warning',['order_code'=>$o['order_code'],'status'=>$o['status']]);$q=$db->query("SELECT gr.id,gr.order_id,gr.receipt_code FROM goods_receipts gr WHERE gr.inventory_sync_status='pending' AND gr.created_at<DATE_SUB(NOW(),INTERVAL 15 MINUTE)");foreach($q->fetchAll() as $g)$found[]=self::issue('INVENTORY_SYNC_PENDING',(int)$g['order_id'],'warning',['receipt_id'=>$g['id'],'receipt_code'=>$g['receipt_code']]);return ['status'=>'success','data'=>['detected'=>count($found),'issues'=>$found]];}
    private static function issue(string $type,int $orderId,string $severity,array $details): array {$db=getDB();$finger=self::fingerprint($type,$orderId,json_encode($details));$q=$db->prepare('INSERT INTO reconciliation_issues(fingerprint,issue_type,severity,order_id,details) VALUES(:fp,:type,:severity,:oid,:details) ON DUPLICATE KEY UPDATE details=VALUES(details),status=IF(status="resolved","open",status)');$q->execute(['fp'=>$finger,'type'=>$type,'severity'=>$severity,'oid'=>$orderId,'details'=>json_encode($details)]);return ['type'=>$type,'order_id'=>$orderId,'fingerprint'=>$finger];}
    public static function issues(int $limit=50): array {$db=getDB();$limit=min(100,max(1,$limit));$q=$db->query("SELECT r.*,o.order_code FROM reconciliation_issues r LEFT JOIN orders o ON o.id=r.order_id WHERE r.status='open' ORDER BY r.detected_at DESC LIMIT {$limit}");return $q->fetchAll();}
    public static function resolveIssue(int $id,int $userId): array {$db=getDB();$q=$db->prepare("UPDATE reconciliation_issues SET status='resolved',resolved_at=NOW(),resolved_by=:uid WHERE id=:id AND status='open'");$q->execute(['uid'=>$userId,'id'=>$id]);return $q->rowCount()?['status'=>'success','message'=>'Issue ditandai selesai.']:['status'=>'error','message'=>'Issue tidak ditemukan atau sudah selesai.'];}
}
