<?php
require_once __DIR__.'/../../models/Procurement.php';
if (!isset($userId)) {
    $userId = (int) ($_SESSION['user_id'] ?? 0);
}
if (!isset($userName)) {
    $userName = (string) ($_SESSION['name'] ?? 'Supplier');
}
$db=getDB();$q=$db->prepare('SELECT * FROM supplier_profiles WHERE supplier_id=:id');$q->execute(['id'=>$userId]);$profile=$q->fetch()?:[];$performance=Procurement::supplierPerformance($userId);
$total=max(1,(int)($performance['total_orders']??0));$completion=round(((int)($performance['completed_orders']??0)/$total)*100,1);
?>
<div class="page-header"><div><h1 class="page-title">Profil & performa supplier</h1><p class="page-description">Supplier master lokal dan indikator operasional berdasarkan transaksi aktual.</p></div></div>
<div class="metric-grid" style="grid-template-columns:repeat(4,minmax(0,1fr))"><div class="metric-card"><div class="metric-label">Total order</div><div class="metric-value mt-4"><?= (int)($performance['total_orders']??0) ?></div></div><div class="metric-card"><div class="metric-label">Completion rate</div><div class="metric-value mt-4"><?= $completion ?>%</div></div><div class="metric-card"><div class="metric-label">Rata-rata pemenuhan</div><div class="metric-value mt-4"><?= round((float)($performance['avg_fulfillment_hours']??0),1) ?> jam</div></div><div class="metric-card"><div class="metric-label">Sengketa terbuka</div><div class="metric-value mt-4"><?= (int)($performance['open_disputes']??0) ?></div></div></div>
<section class="panel max-w-3xl"><div class="panel-header"><h2 class="panel-title">Supplier master</h2></div><form id="profile-form" class="panel-body grid grid-cols-1 md:grid-cols-2 gap-4"><label>Nama usaha<input name="business_name" required value="<?= htmlspecialchars($profile['business_name']??$userName) ?>" class="w-full mt-1"></label><label>Nama kontak<input name="contact_name" value="<?= htmlspecialchars($profile['contact_name']??'') ?>" class="w-full mt-1"></label><label>Telepon<input name="phone" value="<?= htmlspecialchars($profile['phone']??'') ?>" class="w-full mt-1"></label><label>Lead time standar (hari)<input name="lead_time_days" type="number" min="0" max="365" value="<?= (int)($profile['lead_time_days']??1) ?>" class="w-full mt-1"></label><label class="md:col-span-2">Alamat<textarea name="address" rows="3" class="w-full mt-1"><?= htmlspecialchars($profile['address']??'') ?></textarea></label><label class="flex items-center gap-2"><input name="is_active" type="checkbox" value="1" <?= !isset($profile['is_active'])||$profile['is_active']?'checked':'' ?>> Aktif menerima pesanan</label><div class="md:col-span-2"><button class="bg-primary text-white px-5 py-2.5 text-sm font-bold" type="submit">Simpan profil</button></div></form></section>
<script>document.getElementById('profile-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),data=Object.fromEntries(f.entries());data.is_active=f.has('is_active');const r=await apiCall('<?= rtrim(dirname($_SERVER['SCRIPT_NAME']),'/\\') ?>/api/supplier_profile.php','POST',data);showToast(r.message,r.status==='success'?'success':'error');};</script>
